// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhentngyvepsokkfnuzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZW50bmd5dmVwc29ra2ZudXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzE0MTAsImV4cCI6MjA2OTU0NzQxMH0.iKT5IUfiAr2vp9JcjtCvGsr3hugpGBlc8mQ99_kk87A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});